<?php
$allsokenbangames = [];
$letters = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M"];
$n = 0;
while ($n < 128) {
    array_push($allsokenbangames, $letters[floor($n / 10)] . ((string)$n)[strlen($n) - 1]);
    ++$n;
}

$areainfo = array(
    array('moves'=>10,'loc'=>'Garden'),
    array('moves'=>31,'loc'=>'Garden'),
    array('moves'=>15,'loc'=>'Garden'),
    array('moves'=>18,'loc'=>'Garden'),
    array('moves'=>52,'loc'=>'Garden'),
    array('moves'=>73,'loc'=>'Garden'),
    array('moves'=>314,'loc'=>'Garden'),
    array('moves'=>103,'loc'=>'Garden'),
    array('moves'=>48,'loc'=>'Desert'),
    array('moves'=>28,'loc'=>'Desert'),
    array('moves'=>77,'loc'=>'Desert'),
    array('moves'=>28,'loc'=>'Desert'),
    array('moves'=>47,'loc'=>'Desert'),
    array('moves'=>44,'loc'=>'Desert'),
    array('moves'=>113,'loc'=>'Desert'),
    array('moves'=>28,'loc'=>'Desert'),
    array('moves'=>69,'loc'=>'Desert'),
    array('moves'=>145,'loc'=>'Foreston'),
    array('moves'=>68,'loc'=>'Forest Woods'),
    array('moves'=>57,'loc'=>'Forest Woods'),
    array('moves'=>98,'loc'=>'Forest Woods'),
    array('moves'=>73,'loc'=>'Forest Woods'),
    array('moves'=>85,'loc'=>'Forest Woods'),
    array('moves'=>133,'loc'=>'Forest Woods'),
    array('moves'=>103,'loc'=>'Forest Woods'),
    array('moves'=>40,'loc'=>'Forest Woods'),
    array('moves'=>137,'loc'=>'Forest Woods'),
    array('moves'=>46,'loc'=>'Forest Woods'),
    array('moves'=>533,'loc'=>'Forest Woods'),
    array('moves'=>82,'loc'=>'Forest Woods'),
    array('moves'=>10,'loc'=>'Garden'),
    array('moves'=>71,'loc'=>'Garden'),
    array('moves'=>31,'loc'=>'Garden'),
    array('moves'=>26,'loc'=>'Garden'),
    array('moves'=>77,'loc'=>'Garden'),
    array('moves'=>18,'loc'=>'Forest Woods'),
    array('moves'=>28,'loc'=>'Forest Woods'),
    array('moves'=>20,'loc'=>'Forest Woods'),
    array('moves'=>25,'loc'=>'Forest Woods'),
    array('moves'=>10,'loc'=>'Winter Island'),
    array('moves'=>22,'loc'=>'Winter Island'),
    array('moves'=>22,'loc'=>'Winter Island'),
    array('moves'=>20,'loc'=>'Winter Island'),
    array('moves'=>42,'loc'=>'Winter Island'),
    array('moves'=>42,'loc'=>'Winter Island'),
    array('moves'=>10,'loc'=>'Winter Island'),
    array('moves'=>19,'loc'=>'Winter Island'),
    array('moves'=>64,'loc'=>'Winter Island'),
    array('moves'=>14,'loc'=>'Winter Island'),
    array('moves'=>37,'loc'=>'Winter Island'),
    array('moves'=>65,'loc'=>'Winter Island'),
    array('moves'=>104,'loc'=>'Winter Island'),
    array('moves'=>65,'loc'=>'Winter Island'),
    array('moves'=>53,'loc'=>'Winter Island'),
    array('moves'=>85,'loc'=>'Winter Island'),
    array('moves'=>32,'loc'=>'Winter Island'),
    array('moves'=>86,'loc'=>'Winter Island'),
    array('moves'=>145,'loc'=>'Winter Island'),
    array('moves'=>143,'loc'=>'Winter Island'),
    array('moves'=>102,'loc'=>'Winter Island'),
    array('moves'=>259,'loc'=>'Winter Island'),
    array('moves'=>11,'loc'=>'Autumn Island'),
    array('moves'=>25,'loc'=>'Autumn Island'),
    array('moves'=>43,'loc'=>'Autumn Island'),
    array('moves'=>45,'loc'=>'Autumn Island'),
    array('moves'=>55,'loc'=>'Autumn Island'),
    array('moves'=>11,'loc'=>'Autumn Island'),
    array('moves'=>11,'loc'=>'Autumn Island'),
    array('moves'=>61,'loc'=>'Autumn Island'),
    array('moves'=>16,'loc'=>'Autumn Island'),
    array('moves'=>28,'loc'=>'Autumn Island'),
    array('moves'=>47,'loc'=>'Autumn Island Underground'),
    array('moves'=>33,'loc'=>'Autumn Island Underground'),
    array('moves'=>46,'loc'=>'Autumn Island Underground'),
    array('moves'=>74,'loc'=>'Autumn Island Underground'),
    array('moves'=>77,'loc'=>'Autumn Island Underground'),
    array('moves'=>86,'loc'=>'Autumn Island Underground'),
    array('moves'=>330,'loc'=>'Autumn Island Underground'),
    array('moves'=>382,'loc'=>'Autumn Island Underground'),
    array('moves'=>38,'loc'=>'Autumn Island Underground'),
    array('moves'=>84,'loc'=>'Autumn Island Underground'),
    array('moves'=>274,'loc'=>'Autumn Island'),
    array('moves'=>55,'loc'=>'Autumn Island House'),
    array('moves'=>295,'loc'=>'Autumn Island'),
    array('moves'=>46,'loc'=>'Autumn Island'),
    array('moves'=>195,'loc'=>'Autumn Island'),
    array('moves'=>0,'loc'=>'Autumn Island'),
    array('moves'=>31,'loc'=>'Autumn Island Underground'),
    array('moves'=>25,'loc'=>'Autumn Island Underground'),
    array('moves'=>205,'loc'=>'Autumn Island'),
    array('moves'=>65,'loc'=>'Desert'),
    array('moves'=>39,'loc'=>'Desert'),
    array('moves'=>0,'loc'=>'Desert'),
    array('moves'=>122,'loc'=>'Desert'),
    array('moves'=>45,'loc'=>'Desert'),
    array('moves'=>40,'loc'=>'Tower Basement'),
    array('moves'=>60,'loc'=>'Tower Basement'),
    array('moves'=>232,'loc'=>'Tower Basement'),
    array('moves'=>145,'loc'=>'Tower Basement'),
    array('moves'=>999,'loc'=>'Tower Basement'),
    array('moves'=>80,'loc'=>'Tower Basement'),
    array('moves'=>160,'loc'=>'Tower Basement'),
    array('moves'=>0,'loc'=>''),
    array('moves'=>0,'loc'=>''),
    array('moves'=>0,'loc'=>''),
    array('moves'=>0,'loc'=>''),
    array('moves'=>0,'loc'=>''),
    array('moves'=>0,'loc'=>''),
    array('moves'=>0,'loc'=>''),
    array('moves'=>0,'loc'=>''),
    array('moves'=>0,'loc'=>''),
    array('moves'=>0,'loc'=>''),
    array('moves'=>0,'loc'=>''),
    array('moves'=>0,'loc'=>''),
    array('moves'=>0,'loc'=>''),
    array('moves'=>0,'loc'=>''),
    array('moves'=>0,'loc'=>''),
    array('moves'=>0,'loc'=>''),
    array('moves'=>0,'loc'=>''),
    array('moves'=>0,'loc'=>''),
    array('moves'=>0,'loc'=>''),
    array('moves'=>0,'loc'=>'Autumn Island Underground'),
    array('moves'=>0,'loc'=>'Autumn Island Underground'),
    array('moves'=>0,'loc'=>''),
    array('moves'=>0,'loc'=>''),
    array('moves'=>0,'loc'=>''),
    array('moves'=>0,'loc'=>''),
    array('moves'=>0,'loc'=>''))

?>
